bethinkpl/wnl-platform

- app/Http/Forms/SignUpForm.php
- resources/assets/js/payment.js
- resources/assets/sass/_colors.scss
- resources/assets/sass/_styleguide.scss
- resources/assets/sass/_variables.scss
- resources/assets/sass/app.scss
- resources/lang/pl/payment.php
- resources/views/layouts/app.blade.php
- resources/views/layouts/payment.blade.php
- resources/views/payment/confirm-order.blade.php
- resources/views/payment/personal-data.blade.php
- resources/views/payment/select-product.blade.php
- resources/views/payment/tou.blade.php
- resources/views/styleguide.blade.php
- routes/web.php
> Styleguide

- resources/assets/js/components/course/Lesson.vue
- resources/assets/js/components/course/Navigation.vue
- resources/assets/js/store/modules/progress.js
Reflect status in CSS classes of navigation items & mark lessons as complete.
> User Progress

- README.md
- app/Console/Commands/CancelOrder.php
- app/Console/Commands/ChangeOrderPaymentMethod.php
- app/Console/Commands/ListOrders.php
- app/Console/Commands/MarkOrderAsPaid.php
- app/Console/Kernel.php
- app/Models/Order.php
- database/migrations/2017_04_03_114205_add_canceled_to_orders_table.php
* to list all orders - `php artisan orders` 
* or show a specific one - `php artisan orders {order ID}`
* or even a few specific ones `php artisan orders {space separated list of orders IDs}`
* cancel an order - `php artisan order:cancel {order ID}`
* mark an order as paid - `php artisan order:paid {order ID}`
* change order payment method - `php artisan order:method {order ID} {method}`
> Artisan commands for orders

- app/Http/Controllers/Api/Transformers/OrderTransformer.php
- app/Http/Controllers/Payment/ConfirmOrderController.php
- resources/assets/js/app.js
- resources/assets/js/components/chat/Chat.vue
- resources/assets/js/components/global/TextLoader.vue
- resources/assets/js/components/user/MyOrders.vue
- resources/assets/js/components/user/Order.vue
> Do not display empty orders and display canceled ones as canceled

- database/seeds/EditionsTableSeeder.php
- database/seeds/ScreensTableSeeder.php
- resources/assets/js/components/course/Lesson.vue
- resources/assets/js/components/course/Navigation.vue
- resources/assets/js/components/course/screens/End.vue
- resources/assets/js/components/course/screens/Slideshow.vue
- resources/assets/js/components/global/Sidenav.vue
- resources/assets/js/components/global/SidenavItem.vue
- resources/assets/js/components/user/Dropdown.vue
- resources/assets/js/store/modules/progress.js
- resources/assets/js/utils/env.js
- resources/assets/sass/app.scss
Porting important fixes already implemented in demo.
> Demo fixes port

- resources/assets/js/components/chat/Chat.vue
- resources/assets/js/components/chat/Message.vue
- resources/views/layouts/guest.blade.php
1. Zero state message for chat encouraging to start a discussion.
2. Added a date to time format of messages
> Chat UX fixes

- app/Http/Controllers/Api/PrivateApi/Course/ScreensApiController.php
- package.json
- yarn.lock
- Downgrade Vue to 2.2.6
- Comment method to consult with @gitkuba
> Fix npm packages and Screens controller

- package.json
- resources/assets/js/store/modules/form.js
- yarn.lock
+ use a simpler method to clone originalData object in forms
> Update Vue and related packages to the newest version

- package.json
@adamkarminski @gitkuba 
https://media.giphy.com/media/BVStb13YiR5Qs/giphy.gif
> Build | Removing watch from scripts

- resources/assets/js/components/global/Sidenav.vue
- resources/assets/js/components/global/SidenavItem.vue
- resources/assets/js/components/global/form/Submit.vue
- resources/assets/js/components/user/MyAddress.vue
- resources/assets/js/components/user/MyBillingData.vue
- resources/assets/js/components/user/MyPassword.vue
- resources/assets/js/components/user/MyProfile.vue
- resources/assets/js/components/user/Myself.vue
- resources/assets/js/router.js
- Added personal data editing
- Fixed personal data forms
- For now, hide avatar editing on production
> Prepare the master branch to be pushed to production

- app/Listeners/NotifyUser.php
- database/migrations/2017_05_29_165001_create_notifications_table.php
> fix notifications

- resources/assets/js/components/global/Navbar.vue
- resources/assets/js/store/modules/ui.js
* sidenav-trigger (hamburger) shows on mobile + tablet
* controls on the right (search icon etc.) show on tablet + desktop
* breacdrumbs show on desktop
* breadcrumbs are vertically-aligned with logo
@adamkarminski @bognix
> Layout | Navbar based on breakpoints

- resources/assets/js/admin/components/Admin.vue
- resources/assets/js/admin/components/forms/Quill.vue
- resources/assets/js/admin/components/lessons/edit/LessonEditor.vue
- resources/assets/js/admin/components/lessons/edit/ScreensEditor.vue
- resources/assets/js/admin/components/lessons/edit/ScreensList.vue
- resources/assets/js/admin/components/lessons/list/LessonsListItem.vue
- resources/assets/js/app.js
- resources/assets/js/bootstrap.js
- resources/assets/js/components/App.vue
- resources/assets/js/components/course/screens/Html.vue
- resources/assets/js/components/global/form/Form.vue
- resources/assets/js/store/modules/currentUser.js
- resources/assets/sass/_styleguide.scss
- For now, I commented out code that tried to connect with the notifications server as it's not part of our Homestead setup yet.
- Use a correct method that the Quill component available in the Admin app launches on the text-change event.
- For videos embedded via Quill - maintain 16:9 ratio and 100% width.
- Added more options to the default Quill editor toolbar.
> Fix admin quill

- database/seeds/UsersTableSeeder.php
- resources/assets/js/admin/components/forms/Code.vue
- resources/assets/js/admin/components/slides/SlidesEditor.vue
- resources/assets/js/utils/env.js
Improve the questionable UX of slides editing!
> Fix slide editor

- resources/assets/js/components/course/screens/Slideshow.vue
- resources/assets/js/components/global/SidenavItem.vue
> Destroy slideshow when a screen is changed

- resources/assets/js/router.js
@adamkarminski As we talked yesterday.
> Routing | Myself route now redirects to myself/profile

- resources/assets/js/components/course/Lesson.vue
- resources/assets/js/store/modules/course.js
- Provide all methods using screens with an array previously sorted by `order_number`
> Sort screens from the very beginning

- resources/assets/js/admin/components/Sidenav.vue
- resources/assets/js/components/MainNav.vue
- resources/assets/js/components/course/Navigation.vue
- resources/assets/js/components/global/Sidenav.vue
- resources/assets/js/components/global/SidenavSlot.vue
- resources/assets/js/store/modules/ui.js
> Layout | Mobile navigation styling

- resources/assets/js/components/user/MyProfile.vue
- resources/assets/js/components/user/Myself.vue
- resources/assets/js/store/modules/ui.js
- resources/assets/sass/app.scss
> Layout | Mobile user profile

- resources/assets/js/components/chat/ChatRoom.vue
- resources/assets/js/components/chat/PublicChat.vue
- resources/assets/js/components/course/Course.vue
- resources/assets/sass/_variables.scss
- Use tabs for channel names links
- Unify chat toggling icons
- Unify spacing
> Chat layout

- resources/assets/js/components/user/MySettings.vue
- resources/assets/js/services/user.js
- resources/assets/js/store/modules/currentUser.js
- resources/assets/js/store/modules/ui.js
> User Settings | Chat uses setting to open

- resources/assets/js/components/chat/ChatRoom.vue
- resources/assets/sass/app.scss
> Layout | Fireflex

- app/Console/Kernel.php
- app/Http/Controllers/Api/PrivateApi/Quiz/QuizSetsApiController.php
- app/Http/Controllers/Api/PrivateApi/Quiz/QuizStatsApiController.php
- app/Http/Controllers/Api/PrivateApi/User/UserStateApiController.php
- app/Http/Middleware/ApiCache.php
- config/papi.php
- resources/assets/js/components/course/screens/quiz/QuizAnswer.vue
- resources/assets/js/store/modules/quiz.js
- resources/assets/js/utils/env.js
- routes/papi.php
- tests/Api/Quiz/QuizSetsTest.php
- tests/Api/Quiz/QuizStatsTest.php
- tests/Api/User/UserStateTest.php
@bognix @gitkuba - Cache się wciąż nie invaliduje, pomimo dodania `stats` do excluded.
@bognix  - sprawdź proszę ten temat rano. Na razie ogarnąłem tylko tyle, żeby cały quiz się nie wychrzaniał, jeśli statsy nie są dostępne. 🖖
> Quiz | Fix stats caching and displaying

- resources/assets/js/components/course/screens/quiz/QuizAnswer.vue
> Do not display stats if somebody, for some reason, still uses Chrome 49

- resources/assets/js/components/course/screens/quiz/QuizAnswer.vue
> Round the results of a quiz

- resources/assets/js/store/modules/quiz.js
@bognix <3
I've just realised I was restoring comments from Redis as well... :D
> Only restore isResolved and selectedAnswer for quiz questions

- app/Console/Commands/SectionsUpdate.php
- app/Console/Kernel.php
[Updating sections in a slideshow - wiki page](https://github.com/bethinkpl/wnl-platform/wiki/Updating-sections-in-a-slideshow)
@gitkuba Please review and I'll run it in the night.
> A script updating sections in a presentation

- app/Http/Controllers/Api/Transformers/SectionsTransformer.php
- resources/assets/js/components/course/Navigation.vue
- resources/assets/js/components/global/Sidenav.vue
- resources/assets/js/components/global/SidenavItem.vue
Display an information about slides count in a given section.
> Add an information about section length

- app/Console/Commands/SlideshowsRemove.php
- app/Console/Kernel.php
> Add a script that removes a slideshow screen with all belongings

- resources/assets/js/components/course/screens/quiz/Quiz.vue
- resources/assets/js/components/help/LearningHelp.vue
- resources/assets/js/store/modules/quiz.js
It is very important for Darek to be able to react to comments for quiz questions.
> Quiz autoresolve + remove a problematic router link from help

- resources/assets/js/components/course/screens/quiz/QuizList.vue
> Move resetState from getters to actions

- resources/assets/js/components/course/dashboard/DashboardNews.vue
- resources/assets/js/store/modules/currentUser.js
> Add news about workshops deadline

- resources/assets/js/admin/components/slides/SlidesEditor.vue
- resources/assets/js/classes/forms/Form.js
> Forms | Allow Forms to exclude a field from being populated

- app/Console/Commands/InvoicesExport.php
- app/Console/Kernel.php
- app/Models/Invoice.php
> Invoices | Add a script to export invoices as .csv

- resources/assets/js/components/collections/SlidesCarousel.vue
> Collections fixes

- app/Console/Commands/QuizImport.php
@gitkuba review & merge please
EDIT: Nvmd.
> Tags | Tag quiz questions based on a global tag for a quiz set

- resources/assets/js/components/MainNav.vue
- resources/assets/js/components/collections/Collections.vue
- resources/assets/js/components/course/Navigation.vue
- resources/assets/js/components/course/dashboard/NextLesson.vue
- resources/assets/js/components/global/Sidenav.vue
- resources/assets/js/components/global/SidenavGroup.vue
- resources/assets/js/components/global/SidenavItem.vue
- resources/assets/js/components/qna/QnaQuestion.vue
- resources/assets/js/store/modules/course.js
- resources/assets/sass/_styleguide.scss
- resources/assets/sass/_variables.scss
@bkoval - this is a new pull request with a reverted revert. :)
> Navigation | Enable grouping items and groups folding

- resources/assets/js/components/moderators/ModeratorsDashboard.vue
> Moderators Feed | Restore removed dashboard :facepalm:

- resources/assets/js/components/qna/QnaQuestion.vue
@bognix - it's a fix for a situation in which a comment was added to a hidden answer. :)
> Notifactions | Scroll to comment also if an answer is hidden

- app/Traits/EventContextTrait.php
> Notifications | Route context for a commented slide

- resources/assets/js/components/notifications/events/CommentPosted.vue
- resources/assets/js/components/notifications/events/QnaAnswerPosted.vue
- resources/assets/js/components/notifications/events/QnaQuestionPosted.vue
- resources/assets/js/components/notifications/events/ReactionAdded.vue
- resources/assets/js/components/notifications/feeds/personal/PersonalFeed.vue
- resources/assets/js/components/notifications/feeds/personal/PersonalNotification.vue
- resources/assets/js/components/notifications/notification.js
- resources/assets/js/components/quiz/SingleQuestion.vue
- resources/assets/js/i18n/pl/notifications.js
> Notification context

- resources/assets/js/components/course/dashboard/DashboardNews.vue
One of the last news committed to code... I hope!
> News | Add an info about workshops movie

- resources/assets/js/components/chat/Message.vue
- resources/assets/js/components/comments/Comment.vue
- resources/assets/js/slideshow.js
> Fix Safari ESC and <p> margins in Quill generated messages

- package.json
- resources/assets/js/components/notifications/feeds/moderators/ModeratorsNotification.vue
- resources/assets/js/components/notifications/feeds/personal/PersonalNotification.vue
- resources/assets/js/components/notifications/feeds/stream/StreamNotification.vue
- resources/assets/js/components/notifications/notification.js
- resources/assets/js/router.js
- yarn.lock
> Notifications | Unescape HTML entities

- app/Console/Commands/TagsCleanup.php
- app/Console/Kernel.php
[.tsv source](https://docs.google.com/spreadsheets/d/1lPHlJkIfyb15VyRdGttq5mUGmLu9bVA442eF0BUOrFc/edit#gid=0)
> Add an Artisan command to clean-up tags

- resources/assets/js/components/notifications/feeds/questions/QuestionsFeed.vue
- resources/assets/js/components/questions/QuestionsDashboard.vue
- resources/assets/js/components/questions/QuestionsList.vue
- resources/assets/js/components/quiz/QuizList.vue
- resources/assets/js/i18n/pl/questions.js
> Allow users to hide discussions and finish quiz only if a user clicks cancel

- resources/assets/js/admin/components/quizes/QuizQuestionEditor.vue
- resources/assets/js/components/global/form/Form.vue
- In form we compare not only fields but also attached data to determine if something changed
> Quiz Editor | Tweaks and tricks

- app/Console/Kernel.php
- app/Exceptions/Handler.php
- app/Models/Comment.php
- app/Models/QnaAnswer.php
- app/Models/QnaQuestion.php
- composer.json
This reverts commit 8be4da73376e80eb7927f1373bbe498244b5db8c.
> Upgrade to laravel 5.5 once again :tada:

- resources/assets/js/components/global/form/Quill.vue
> Mentions | Use userId, not profileId

- app/Console/Commands/ListOrders.php
> Allow to list only remindable or cancelable orders

- app/Console/Commands/ListOrders.php
> Add an option to list potentially paid orders

- app/Console/Commands/CategoriesTags.php
- app/Console/Commands/SlidesFromCategory.php
- app/Console/Kernel.php
On production run following commands:
* add category tags to lessons
`php artisan tags:fromCategories`
* build presentables
`php artisan slides:fromCategory`
> add category tag to lesson and fix slides order in collections

- resources/assets/js/components/course/dashboard/DashboardNews.vue
> Moderators announcement

- app/Console/Commands/ListOrders.php
> Add an option to list all orders with outstanding instalments

- app/Console/Commands/LessonTags.php
What to do to fix ginekologia:
1. Rename categories
- get categories from Ginekologia:
```select name, id from categories where parent_id = 4```
- rename categories
```update categories set name = "Ginekologia 2" where id = 34;```
(insert correct ID and correct category name (from Ginekologia 2 to 5)
2. Attach lesson tags to Quiz Sets and Lessons (add Ginekologia % tag to Quiz Set and lesson)
```php artisan tags:fromLessons```
3. Build presentable for new lesson tags
```php artisan slides:fromCategory```
> add lesson tag to ginekologia and update quiz questions and presentables

- app/Console/Commands/QuizExport.php
> Allow exporting quiz questions by a tag name

- app/Console/Commands/LinkQuestionsToSlides.php
- app/Console/Commands/SlidesImport.php
- lib/SlideParser/Parser.php
@gitkuba @bognix - you can jump in with an initial code review.
TODO:
> Fix questions tags parsing

- app/Console/Commands/LessonUser.php
- app/Models/Lesson.php
- app/Models/LessonUserAccess.php
- database/migrations/2018_02_10_054239_add_access_to_lesson_user_access_table.php
> Allow to selectively grant and block access to lessons

- app/Http/Controllers/Auth/LoginController.php
> Prevent from keeping tons of old session IDs in mysql;

- app/Http/Controllers/Api/Transformers/SlideTransformer.php
- resources/assets/js/components/course/screens/slideshow/LinkedQuestions.vue
- resources/assets/js/components/course/screens/slideshow/Slideshow.vue
> Display linked questions next to slides

- resources/assets/js/components/chat/MessageForm.vue
- resources/assets/js/components/chat/PrivateChatMessageForm.vue
https://github.com/bethinkpl/wnl-chat/pull/6/files
> Messages length validation

- app/Console/Commands/ProcessChatQueue.php
- app/Http/Controllers/Api/PrivateApi/ChatRoomsApiController.php
- app/Http/Controllers/Api/Transformers/ChatRoomTransformer.php
- resources/assets/js/components/chat/MessageForm.vue
- resources/assets/js/components/chat/PrivateChat.vue
- resources/assets/js/components/messages/ConversationsList.vue
- resources/assets/js/components/messages/MessagesDashboard.vue
- resources/assets/js/plugins/socket.js
- resources/assets/js/store/modules/chatMessages.js
related PR https://github.com/bethinkpl/wnl-chat/pull/10
> weird counter + public / private room handling

- app/Console/Commands/SetUsersLessons.php
- app/Http/Controllers/Api/PrivateApi/SlidesApiController.php
- app/Jobs/OrderPaid.php
- app/Models/Lesson.php
- app/Policies/Chat/ChatRoomPolicy.php
- resources/assets/js/store/modules/course.js
> Lesson product

- resources/assets/js/components/global/SplashScreen.vue
@bognix - please review and release <3
> Update the splashscreens copy

- app/Models/Order.php
- resources/assets/js/components/user/Order.vue
- resources/views/payment/confirm-order.blade.php
> Update copy and counting of instalments

- app/Console/Commands/AddressesExport.php
> Add more options to the addresses export

- app/Console/Commands/ListOrders.php
- resources/views/payment/payment-hero.blade.php
@preziu @gitkuba @bognix Review please. :)
> Add updated_at to ListOrders AND update notification about album delivery

- resources/assets/js/components/course/Screen.vue
- resources/assets/js/components/course/screens/slideshow/Slideshow.vue
> don't load new presentation when on the same screen

- resources/assets/js/store/modules/progress.js
> check for lesson availability in progress

- app/Jobs/OrderPaid.php
- app/Notifications/QueueJobFailed.php
- app/Providers/AppServiceProvider.php
> Send notification to slack when queued job fails

- .gitignore
- app/Console/Commands/InvoicesExportToJpk.php
> Jpk improvements

- resources/assets/js/components/global/SplashScreen.vue
> Update the splashscreen message

- app/Console/Commands/ExamsResults.php
- app/Console/Commands/QuizImport.php
- app/Console/Commands/SetUsersLessons.php
- app/Http/Controllers/Api/Filters/ByTaxonomy/ByTaxonomyFilter.php
- app/Http/Controllers/Api/PrivateApi/QuizQuestionsApiController.php
- app/Http/Controllers/Api/PrivateApi/UserQuizResultsApiController.php
- resources/assets/js/components/course/screens/MockExam.vue
- resources/assets/js/components/questions/QuestionsDashboard.vue
- resources/assets/js/components/questions/QuestionsList.vue
- resources/assets/js/i18n/pl/questions.js
Before Release
- Add meta to "Próbny LEK" screen
```
update screens set meta='{"resources": [{"id": 538, "name": "exam_tag_id"}]}' where id = 442;
```
- Create new Group and new Lesson for "Wstępny LEK"
```
insert into groups (name, course_id, order_number) values ("Wstępny LEK", 1, 0);
insert into lessons (name, group_id, is_required, order_number) values ("Wstępny LEK", 16, 1, 0);
```
- Add a mockExam screen to a lesson
- Import Quiz Questions from S3
```
php artisan quiz:import probny/Wstepny-LEK-czerwiec-2018.tsv --addNewTags
```
- Add tag to tag_taxonomy (replace 538 with newly created tag id)
```
insert into tags_taxonomy (tag_id, parent_tag_id, taxonomy_id) values (538,0, 2);
```
- Add meta with exam tag id to created screen
- Give users access to "Wstępny LEK" lesson by running: …
> Preview all exams

- app/Http/Forms/SignUpForm.php
- resources/lang/pl/payment.php
> Fix links to TOU and Privacy Policy

- resources/assets/js/admin/components/quizes/QuizQuestionEditor.vue
- resources/assets/js/components/global/form/Quill.vue
formSubmit method was called before the props were updated inside the Form.vue child component. 
As a fix I call the formSubmit method when I'm sure props are recomputed.
> Fix Double Save Click in QuizQuestionEditor

- app/Models/Invoice.php
- database/migrations/2018_09_02_091640_add_meta_to_invoices_table.php
- lib/Invoice/Invoice.php
https://bethink.atlassian.net/browse/PLAT-463
> [PLAT-463] Save all invoice data

- app/Http/Controllers/Payment/ConfirmOrderController.php
- app/Http/Controllers/Payment/PersonalDataController.php
- resources/assets/js/components/user/MyOrders.vue
- resources/views/payment/confirm-order.blade.php
- resources/views/payment/layout.blade.php
- resources/views/payment/select-product.blade.php
- resources/views/tracking.blade.php
https://github.com/bethinkpl/ansible/pull/27/files
> Add FB Tracking Pixel

- app/Http/Controllers/Api/Transformers/OrderTransformer.php
- app/Http/Controllers/Payment/ConfirmOrderController.php
- lib/Invoice/Invoice.php
- resources/assets/js/components/user/Order.vue
When releasing remember to **remove album's instalments row from payment_method_product table**
> PLAT-611 | Disable instalments for album and remove note about access in invoice for album's instalment

- resources/assets/js/components/course/screens/slideshow/Annotations.vue
- resources/assets/js/components/course/screens/slideshow/Slideshow.vue
> Position the comments loading spinner in a more logical place

- app/Console/Commands/FixMissingInvoiceFiles.php
- app/Console/Commands/InvoiceRender.php
- app/Console/Commands/MigrateInvoiceType.php
- app/Models/Invoice.php
- database/migrations/2018_10_10_140959_add_type_to_invoices.php
- lib/Invoice/Invoice.php
> [PLAT-616] Render missing invoices

- resources/assets/js/components/questions/QuestionsTest.vue
- resources/assets/js/components/quiz/QuizList.vue
> PLAT-678 Hide questions count for a paginated QuestionsTest

- app/Console/Commands/TagsCreateAndAttachToQuestions.php
> PLAT-680 Command that attaches new or existing tags to quiz questions

- resources/assets/js/plugins/events-tracker.js
This reverts commit 1acfef28c5eb8d8fb3c5a3ba12384ea445bccec1.
DON'T MERGE until https://github.com/bethinkpl/sad-server/pull/2 is deployed
> PLAT-676 | Revert "send only expected route params"

- app/Policies/User/UserAddressPolicy.php
- resources/assets/js/admin/admin.js
- resources/assets/js/admin/components/users/UserAddress.vue
- resources/assets/js/components/user/PersonalData.vue
- resources/assets/js/components/user/UserAddress.vue
- resources/assets/js/store/modules/form.js
> PLAT-743 | admin edit user address

- app/Models/User.php
Admins and moderators subscription is always active, even if there are no min or max dates set.
> Admins and moderators subscription is always active

- resources/assets/js/components/global/form/Form.vue
- resources/assets/js/mixins/reaction.js
Change notification for not found response when addind comment or reaction to a non-existent record.
> [PLAT-772] Change notification for not found response

- resources/assets/js/admin/components/dashboardNews/DashboardNewsEdit.vue
- resources/assets/js/mixins/dashboard-news-message-arguments.js
- resources/assets/js/utils/injectArguments.js
- resources/assets/js/utils/injectArguments.spec.js
https://bethink.atlassian.net/browse/PLAT-810
> PLAT-810 | Add description of available message arguments

- .editorconfig
> Use one tab instead of two for attributes indentation

- .editorconfig
- .gitignore
- _ide_helper.php
- _ide_helper_models.php
- app/Models/Structure.php
- app/Providers/AppServiceProvider.php
- composer.json
- composer.lock
- config/app.php
- config/ide-helper.php
https://github.com/barryvdh/laravel-ide-helper
> Install laravel-ide-helper and generate docs

- app/Http/Controllers/Api/Filters/TaggableFilter.php
- app/Http/Controllers/Api/Transformers/TaggableTransformer.php
- resources/assets/js/admin/components/lists/PaginatedList.vue
- resources/assets/js/admin/components/lists/PaginatedSortableTable.vue
- resources/assets/js/admin/components/lists/SortableTable.vue
- resources/assets/js/admin/components/slides/SlideEditor.vue
- resources/assets/js/admin/components/tags/TagEditor.vue
- routes/papi.php
https://bethink.atlassian.net/browse/PLAT-851
> PLAT-851 | Show related taggables list in tag editor

- app/Http/Controllers/Api/PrivateApi/TaggablesApiController.php
- app/Http/Controllers/Api/PrivateApi/TagsApiController.php
- app/Models/Tag.php
- resources/assets/js/admin/components/tags/TagEditor.vue
- resources/assets/js/admin/components/tags/TaggablesMover.vue
- resources/lang/pl/tags.php
https://bethink.atlassian.net/browse/PLAT-863
Follow up to https://github.com/bethinkpl/wnl-platform/pull/1192
> PLAT-863 | Enable tag deletion

- resources/assets/js/components/global/form/Form.vue
Fixes: `/admin/app/users/5#address`
> Fix form population from value

- app/Console/Commands/ScoutImportAll.php
Introduce `scout:import-all` command to import all searchable models to search index
TODO:
> PLAT-902 | Add scout:import-all command

- app/Console/Kernel.php
See https://pushgateway.bethink.tech/ for an example how it looks there.
> PLAT-934 | Notify Prometheus Pushgateway after scheduled job is run

- README.md
The last run was 2 years ago: https://travis-ci.org/bethinkpl/wnl-platform/branches
> Remove build status from README

- .eslintrc.js
- package.json
- resources/assets/js/admin/components/forms/Checkbox.vue
- resources/assets/js/admin/components/forms/Code.vue
- resources/assets/js/admin/components/forms/Input.vue
- resources/assets/js/admin/components/forms/Textarea.vue
- resources/assets/js/admin/components/quizes/QuizQuestionEditor.vue
- resources/assets/js/admin/components/slides/annotations/AnnotationsEditor.vue
- resources/assets/js/admin/components/users/UserPlan.vue
- resources/assets/js/components/MainNav.vue
- resources/assets/js/components/chat/PublicChat.vue
- resources/assets/js/components/collections/Collections.vue
- resources/assets/js/components/global/Autocomplete.vue
- resources/assets/js/components/global/Navbar.vue
- resources/assets/js/components/global/Sidenav.vue
- resources/assets/js/components/global/SidenavSlot.vue
- resources/assets/js/components/global/Toggler.vue
- resources/assets/js/components/global/accordion/AccordionItem.vue
- resources/assets/js/components/global/form/Check.vue
- resources/assets/js/components/global/form/Sortable.vue
- resources/assets/js/components/notifications/feeds/chat/ChatFeed.vue
- resources/assets/js/components/notifications/feeds/personal/PersonalFeed.vue
- resources/assets/js/components/qna/QnaQuestion.vue
- resources/assets/js/components/questions/QuestionsDashboard.vue
- resources/assets/js/components/questions/QuestionsPlanner.vue
- resources/assets/js/components/user/Notifications.vue
- resources/assets/js/components/users/UserProfile.vue
- resources/assets/js/components/users/UserProfileModal.vue
I only enabled the rules that shouldn't cause many conflicts with current PRs and don't need much testing.
> Enable part of vue/strongly-recommended eslint rules

- app/Console/Commands/ReorderSections.php
> PLAT-964 | Update desc

- app/Console/Commands/ExamsResults.php
- app/Jobs/CalculateExamResults.php
It's not fixing the problem on production but at least gives us a way to fix it afterwards.
> PLAT-965 | fix command for calculating final lek

- resources/assets/js/admin/components/taxonomies/TaxonomyTermEditorAdd.vue
- resources/assets/js/admin/components/taxonomies/TaxonomyTermEditorCurrentTerm.vue
- resources/assets/js/admin/components/taxonomies/TaxonomyTermEditorDelete.vue
- resources/assets/js/admin/components/taxonomies/TaxonomyTermEditorEdit.vue
https://bethink.atlassian.net/browse/PLAT-948
> PLAT-948 | Display info about current term in taxonomy term editor

- nfs_docker_osx.sh
@rogatty 👉🏼 https://github.com/bethinkpl/wnl-platform/wiki/Set-up-dev-environment#set-up-nfs-to-improve-docker-performance-on-mac-os-optional
> Add script for setting up NFS on Mac

- app/Console/Commands/ClearRedisActiveFiltersKeys.php
- app/Console/Commands/MigrateRedisKeys.php
- app/Http/Controllers/Api/Filters/Quiz/PlannedFilter.php
- app/Http/Controllers/Api/Filters/Quiz/ResolutionFilter.php
- resources/assets/js/store/modules/questions.js
+ Only call the method if you know it's name.
> Create command to clean up badly stored filters

- .travis.install-mysql-5.7.sh
- Dockerfile.php
- plus bump newrelic agent version because old one doesn't exists anymore
> run php-fpm container as non root

- package.json
- yarn.lock
Changes merged from upstream: https://github.com/bethinkpl/laravel-mix/commit/586e5f234a8d5f59ce9084a1ce841b937ee3dc42
See https://github.com/webpack-contrib/terser-webpack-plugin#cache and https://github.com/webpack-contrib/terser-webpack-plugin#parallel
```
node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
Before:
Compiled successfully in 97154ms
After:
Compiled successfully in 54610ms
```
> Upgrade laravel-mix

- app/Http/Controllers/Api/Transformers/FlashcardsSetTransformer.php
- app/Models/Flashcard.php
- app/Models/FlashcardsSet.php
Follow up after https://github.com/bethinkpl/wnl-platform/pull/1298
> PLAT-942 | Fix sorting for flashcards set

- app/Console/Commands/QuizExport.php
https://bethink.atlassian.net/browse/PLAT-1018
Use chunks to avoid memory being exhausted.
Here is how it looks for LEK:
```
s3://wnl-platform-staging/exports/quiz/QuizQuestions-all.tsv
```
> PLAT-1018 | Allow export of all quiz questions

- app/Console/Commands/CouponsAttachProducts.php
- app/Console/Commands/UserClone.php
- app/Http/Controllers/Payment/PersonalDataController.php
- app/Http/Controllers/Payment/SelectProductController.php
- database/seeds/ExampleData.php
- database/seeds/InstalmentsSeeder.php
- database/seeds/PaymentMethodsSeeder.php
- resources/lang/pl/payment.php
- resources/views/payment/info-links.blade.php
- resources/views/payment/select-product.blade.php
- tests/Browser/Pages/Payment/SelectProductPage.php
- tests/Browser/Tests/Payment/Modules/PersonalDataModule.php
- tests/Browser/Tests/Payment/Modules/SelectProductModule.php
- tests/Browser/Tests/Payment/PaymentTest.php
https://bethink.atlassian.net/browse/PLAT-1096
> PLAT-1096 | Remove wnl-onsite from code

- resources/views/mail/account-suspended-unpaid-instalment.blade.php
- resources/views/mail/certificate-final.blade.php
- resources/views/mail/layout.blade.php
- resources/views/mail/payment-reminder-instalment.blade.php
- resources/views/mail/payment-reminder-online.blade.php
- resources/views/mail/payment-reminder-transfer.blade.php
- resources/views/mail/refund.blade.php
- resources/views/mail/sign-up-confirmation.blade.php
- resources/views/mail/study-buddy-usage.blade.php
- resources/views/mail/study-buddy-without-invoice.blade.php
- resources/views/mail/study-group.blade.php
This PR updates some misleading content and expired links. I didn't have time to test the content though, so please check the changed e-mails and make changes if necessary.
I created another ticket for sending an extra e-mail when somebody gets a study buddy coupon: https://bethink.atlassian.net/browse/PLAT-1119
> Update content of e-mails and introduce a new one for Study Buddy

- resources/assets/js/components/global/modals/SatisfactionGuaranteeModal.vue
- resources/assets/js/i18n/pl/ui.js
- resources/lang/pl/payment.php
- resources/views/payment/voucher.blade.php
After meeting with marketing team they asked me for minor changes in copies.
The change of the copy in modal buttons forced me to update the styling as well.
> update copies in checkout and modal styling

- database/migrations/2019_04_05_082930_orders_canceled_not_nullable.php
The generated schema doesn't match the production schema. Let's unify it
> PLAT-1184 | Fix orders tabel schema

- resources/assets/js/admin/components/products/ProductPaymentMethods.vue
We were mutating dates in component's data instead of the value passed to datepicker. Dates modified with datepicker were fixed inside it but we sent the unmodified ones in incorrect format to the server.
> Fix instalments datepicker

- tests/Browser/Pages/Payment/MyOrdersPage.php
- tests/Browser/Tests/Payment/Modules/MyOrdersModule.php
- tests/Browser/Tests/Payment/PaymentTest.php
I forgot to push it to https://github.com/bethinkpl/wnl-platform/pull/1413 🤷‍♂️
> PLAT-922 | Add tests for instalments distribution after coupon applied

- app/Http/Controllers/Payment/PersonalDataController.php
- app/Jobs/OrderStudyBuddy.php
- tests/BethinkBrowser.php
- tests/Browser/Tests/Payment/Modules/MyOrdersModule.php
- tests/Browser/Tests/Payment/PaymentTest.php
https://bethink.atlassian.net/browse/PLAT-1177
> PLAT-1177 | Generate study buddy after order is paid

- resources/assets/js/components/course/screens/slideshow/Slideshow.vue
https://bethink.atlassian.net/browse/PLAT-1118
> PLAT-1118 | Setup slide comments after slideshow refresh

- app/Http/Controllers/Api/Transformers/UserTransformer.php
- resources/assets/js/components/App.vue
- resources/assets/js/components/course/Course.vue
- resources/assets/js/components/global/splashscreens/SplashScreen.vue
- resources/assets/js/components/global/splashscreens/UpcomingEdition.vue
- resources/assets/js/components/onboarding/Onboarding.vue
- resources/assets/js/components/user/Order.vue
- resources/assets/js/router.js
- resources/assets/js/store/modules/course.js
- resources/assets/js/store/modules/currentUser.js
https://bethink.atlassian.net/browse/PLAT-1167
> PLAT-1167 | Stop making requests that we know will end up with 403

- app/Http/Controllers/Api/PrivateApi/CourseStructureNodesApiController.php
- resources/assets/js/components/course/dashboard/YourProgress.vue
- resources/assets/js/components/user/plan/LessonsPlanner.vue
- resources/assets/js/components/user/plan/ManualPlanNodeItem.vue
- resources/assets/js/components/user/plan/OpenAllPlan.vue
- resources/assets/js/i18n/pl/lessonsAvailability.js
- resources/assets/js/store/modules/course.js
- tests/Api/Course/CourseStructureNodesTest.php
https://bethink.atlassian.net/browse/PLAT-1185
> PLAT-1185 | Hide not accessible lessons from non-admins

- .travis.yml
- lib/Invoice/Invoice.php
- lib/SlideParser/Parser.php
- routes/console.php
1. Fix:
```
In Parser.php line 577:
Undefined variable: image
```
2. Enable Larastan on `/checks`, `/lib` and `/routes` because it would catch the issue.
3. Fix the linter issues.
4. Bonus: fix corrective invoices.
> Enable Larastan for more directories and fix Parser

- app/Console/Commands/StoreProgress.php
For some time we're storing in redis data without `status` for sections, we have to handle it somehow now. Example data in redis:
```
"{\"status\":\"in-progress\",\"route\":{\"name\":\"lessons\",\"params\":{\"courseId\":\"1\",\"lessonId\":\"8\",\"screenId\":\"687\",\"slide\":\"62\"},\"query\":{\"slide\":\"30269\"},\"meta\":[]},\"screens\":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,nul …
```
> PLAT-1264 | Fill in missing status in progress:store
