resources/assets/js/components/course/screens/Slideshow.vue
resources/assets/sass/app.scss

Since Safari and Chrome on iOS do not support [Fullscreen API](http://caniuse.com/#search=fullscreen), I implemented a "faux fullscreen mode", in which the presentation is positioned as fixed on top of everything.
Since the problem only occurs on touch devices, you can close the fullscreen using an x button in top right corner, but the Esc key doesn't work (no need for that).

Create a faux fullscreen mode for iOS

---

resources/assets/js/components/course/screens/Html.vue

Without it, if you had more than 1 screen of Html type, only the first iframe is scaled to fullwidth.

Wrap embed elements in fullwidth container on component update

---

resources/assets/js/components/App.vue
resources/assets/js/router.js

It's less than ideal, as the links actually redirect a user away from the page, but allows for a less surprising navigation and allow for quick navigation between lessons.
In short - if a user goes on mobile to a "root route" i.e. Course overview, Collections or Account - the drawer is not closed but remains with a new route navigation.

Mobile UI | PoC of a persisting side nav drawer

---

resources/assets/js/components/collections/SlidesCarousel.vue

@bognix - I know it violates the `data down, action up` principle, but I don't see another way to do it now. Let's figure it out!

Collections | Fix going back to a previously clicked bookmarked slide

---

resources/assets/js/components/collections/Collections.vue
resources/assets/js/components/collections/SlidesCarousel.vue
resources/assets/js/components/course/screens/slideshow/Slideshow.vue
resources/assets/js/store/modules/comments.js

1. Hiding slideshow with no bookmarked slides wasn't working and this allowed people to use Collections to view slideshows not yet available to them.
2. Collections always loaded the first and heaviest category - Cardiology. Slower machines (e.g. iPhone 6s, so not THAT slow) were not able to process it. A simple placeholder was introduced for that reason.

Fix major bugs in first release of Collections

---

resources/assets/js/components/notifications/feeds/stream/StreamNotification.vue
resources/assets/js/i18n/pl/notifications.js

@bognix - The best solution would be to mark a notification as seen/read not at click but when you visit a page with a `&notification` param in URL. But! That would require synchronizing which I decided not to implement now, as we have a lot of work with Search.
This solution is definitely suboptimal, but IMO - good enough.
Let me know what you think. :)

Notifications | Open stream notifications in a new tab

---

resources/assets/sass/_styleguide.scss

The problem origins in Quill not nesting `ol` lists but adding a `.ql-indent-#{$i}` class to every indentation level. If you want to have nested lists that **actually** reset counters, you need to implement Quill editor's styling-style of these lists.

Fix displaying nested lists from Quill editor

---

app/Http/Controllers/Api/PrivateApi/QuizQuestionsApiController.php

@bognix - in the end, it was ALMOST a simple tagId change. ;)

Use correct conditions to retrieve a result of an exam

---

app/Console/Commands/AddressesExport.php
app/Console/Commands/OrdersShippingStatus.php
database/migrations/2018_05_22_112453_add_shipping_status_to_orders_table.php

The migration creates a new column `shipping_status` in the orders table. The PR also includes a command that allows changing the status for given orders IDs.
TODO:

Shipping status

---

app/Listeners/Handlers/CommentPostedHandler.php
app/Listeners/UserNotificationsGate.php
app/Traits/EventContextTrait.php

Były 2 problemy:
- notyfikacje o komentarzach do slajdów nie miały prawa działać ponieważ slajdy nie posiadają "commentableAuthor". Bez sprawdzenia czy autor istnieje dorzucaliśmy go do listy "$exluded". Dorzucenie tam null powodowało że żaden użytkownik nie był zwracany dla User::whereNotIn('id' , $excluded)
- notyfikacje o QnaQuestion ignorowały czy użytkownik rozpoczął daną lekcję ponieważ struktura "contextu" tego eventu jest inna niż innych ze względu na "dynamic context".

Fix notifications private stream

---

app/Console/Commands/SlidesFromCategory.php
app/Http/Controllers/Api/Concerns/TranslatesApiQueries.php
resources/assets/js/store/modules/collections.js

Problem:
- Medycyna Rodzinna 3 ma 2 prezentacje ale obecny skrypt do budowania prezentacji dla kategorii wspierał tylko jeden screen typu slideshow (zawsze pierwszy)
Rozwiązanie:
- poprawienie skryptu żeby brał pod uwagę wszystkie prezentacje z lekcji tworząc prezentację dla kategorii
- poprawienie skryptu żeby można było go uruchomić tylko dla jednej kategorii
- zwracane slajdy w widoku kolekcji są posegregowane wg order_number w prezentacji kategorii zamiast po slide id

update command and collections to support lessons with more than one presentation

---

docker-compose.yaml

Instead of creating directory structure on our local machine that will match the docker-compose configuration I would like to propose to make the paths configurable via env variable.
For instance for directory structure:
```
- home/
-- user/
--- git/
---- bethink/
----- wnl-platform
----- wnl-chat
----- wnl-sad-server
--- data/
---- bethink/
----- nginx/
----- mysql/
```
The possible values for env variables are:
```
LOCAL_CODE_PATH=/home/user/git/bethink
LOCAL_DEV_PATH=/home/user/data/bethink
CONTAINER_CODE_PATH=/code/bethink/
```
After merging this PR make sure you have following changes:
- updated the `platform.conf` file for nginx
- added `CONTAINER_CODE_PATH` environment variable in `wnl-platform/.env` file

enable custom directory structure inside docker containers

---

app/Console/Commands/OrdersHandleUnpaid.php
resources/assets/js/components/global/GlobalAlerts.vue
resources/lang/pl/site_wide_messages.php

https://bethink.atlassian.net/browse/PLAT-759
`<strong>` is set to black in bulma so I had to override it.

PLAT-759 | Display due date in the unpaid instalment reminder

---

resources/assets/js/admin/components/dashboardNews/DashboardNewsEdit.vue
resources/assets/js/components/course/dashboard/DashboardNews.vue
resources/assets/js/components/course/dashboard/DashboardNewsContent.vue
resources/assets/js/components/course/dashboard/NextLesson.vue
resources/assets/js/components/notifications/feeds/stream/StreamNotification.vue
resources/assets/js/components/questions/QuestionsPlanner.vue
resources/assets/js/consts/events_map/context.json

https://bethink.atlassian.net/browse/PLAT-796
- Use https://dennisreimann.de/articles/delegating-html-links-to-vue-router.html to open relative URLs without reloading the page
- Track open, close and click_link in dashboard news
- Fix events which were using `actions` instead of `action`

PLAT-796 | Track dashboard news events

---

resources/assets/js/store/modules/quiz.js

We call this method when there are no questions in the collection: https://github.com/bethinkpl/wnl-platform/blob/898c2af1b5301e3ea107b1d97abd7f4f42f72fde/resources/assets/js/components/collections/Collections.vue#L277

Fix loading state for questions on Collections

---

resources/assets/js/components/global/TextButton.vue

https://bethink.atlassian.net/browse/PLAT-897
`.icon` class is used a lot and this was leaking:
```
.icon { height: auto }
```

PLAT-897 | Fix styles for .icon class by not leaking text button styles

---

resources/assets/js/store/modules/comments.js

When calling _.uniq make sure we are comparing the same types
After adding a comment to a slide with ID `x` we do following operations:
- we add it to comments/comments state
- we push it to slideshow/slides[x]/comments array
The problem was that newly created comment had an ID stored as an integer and the old comments have ids stored as strings in slideshow/slides[x]/comments array
When calling _.uniq method I want to make sure we are compering the same types.
Alternative approach would be to don't concat the old commentable comments with newly fetched ones after slide change. However this method is widely used in many modules and I'm afraid of side effects.

PLAT-874 | Double comments

---

app/Console/Commands/ReorderSections.php

When we were fetching slides for sections we were taking them in the default Mysql order which isn't the same as `order_number`. We use those screens later to update order in the presentation: https://github.com/bethinkpl/wnl-platform/blob/c27353f3fa225cce9e3ba99dd174f8622681b97d/app/Console/Commands/ReorderSections.php#L98

PLAT-964 | Fix resetting slides order

---

resources/assets/js/components/course/screens/MockExam.vue

Motivation:
Remove router-link from link to mocked exam. Without router link user can't open mock exam in new tab.
Why do we want to prevent opening in new tab? Because we pass a lot of props to the exam view and we don't want to loose them, and new tab is a new context.

Disable opening mock exam in new tab

---

app/Console/Commands/ProcessChatQueue.php

`Consumer::consume` exits if there are no messages to consume and the `persistent` option isn't set:
https://github.com/bschmitt/laravel-amqp/blob/1a7dfb4498e6a5543d70fddb4e1199c9ab33d267/src/Consumer.php#L32-L34
We don't want to do that, because k8s pod restarts every time it happens.

Stop exiting chat-queue-worker when there are no messages to consume

---

app/Models/Category.php
app/Models/Section.php
app/Models/Slideshow.php
app/Models/Subsection.php

`Slide` model doesn't contain `order_number` column, so we cannot add `OrderByOrderNumberScope` there. It's funny but it works for this case. Unfortunately, it fails when querying `Slide` model directly.
For some reason, Laravel skips `Presentable` model definition when analyzing `morphToMany` relation.
**While testing, make sure to clear cache!**

PLAT-1050 | Add default order to slides morphed by presentables

---

resources/views/payment/voucher.blade.php
tests/Browser/Pages/Payment/VoucherPage.php

```
...E..EEEE...                                                     13 / 13 (100%)
Time: 2.72 minutes, Memory: 40.00 MB
There were 5 errors:
1) Tests\Browser\Tests\Payment\PaymentTest::testLogInEditDataAndOrder
Facebook\WebDriver\Exception\NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"body .voucher-skip a"}
...
```

Fix voucher page selectors in browser tests

---

app/Http/Kernel.php
app/Providers/RouteServiceProvider.php
composer.json
composer.lock
config/api.php
config/cors.php
routes/api.php

Works fine in console on https://bethink.staging.wpengine.com/ and https://wiecejnizlek.pl/
```
let x = await fetch("https://lek.wiecejnizlek.pl/api/v1/products/current");
Access to fetch at 'https://lek.wiecejnizlek.pl/api/v1/products/current' from origin 'https://wiecejnizlek.pl' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
```
let x = await fetch("https://staging.wiecejnizlek.pl/api/v1/products/current");
let y = await x.json();
y.find(product => product.slug === 'wnl-online').quantity;
674
```

PLAT-1239 | Use CORS middleware in products list API
